services:
  postgres:
    image: postgres:16
    container_name: postgres-16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  go-server-scaffold:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: server
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata: